-- =============================================================================
-- 0018_review_tokens.sql — Embedded Deployed Review Mode (U2)
-- =============================================================================
-- Short-lived, single-use, preview-scoped tokens minted SERVER-SIDE at the /s
-- hop (first-party) and carried to the customer's deploy origin in the redirect
-- URL FRAGMENT. The overlay exchanges the token (U3) for a preview-scoped
-- session; the token is NOT the write credential. Minting first-party means the
-- guest link_secret is validated here and NEVER forwarded to the deploy origin.
--
-- The opaque token value is generated by the Next /s route (server-side, Web
-- Crypto) and passed in as p_token — so the DB does not depend on pgcrypto.
--
-- House style mirrors register_preview_tunnel (0011) / register_deploy_target
-- (0017): SECURITY DEFINER + set search_path = '' + schema-qualified + revoke
-- from public + targeted grants. Granted to anon AND authenticated (guests are
-- anonymous/none, members are authenticated via the cookie-bound server client).
-- =============================================================================

create table if not exists public.review_tokens (
  id             uuid primary key default gen_random_uuid(),
  token          text not null unique,
  preview_id     uuid not null references public.previews (id) on delete cascade,
  role           text not null check (role in ('member', 'guest')),
  member_user_id uuid references auth.users (id) on delete set null,
  display_name   text not null,
  expires_at     timestamptz not null,
  used_at        timestamptz,
  created_at     timestamptz not null default now()
);

create index if not exists review_tokens_token_idx on public.review_tokens (token);
create index if not exists review_tokens_preview_id_idx on public.review_tokens (preview_id);

create or replace function public.mint_review_token(
  p_slug        text,
  p_token       text,
  p_link_secret text default null
)
returns table (token text, deploy_url text, role text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid     uuid := (select auth.uid());
  v_preview public.previews%rowtype;
  v_role    text;
  v_member  uuid;
  v_name    text;
begin
  select * into v_preview from public.previews where slug = p_slug;
  if not found then
    raise exception 'preview_not_found';
  end if;

  -- Only previews WITH a registered deploy target take the embedded path; all
  -- others raise not_embeddable so /s falls back to the (dormant) tunnel path
  -- unchanged. Checked BEFORE access so non-embedded previews are untouched.
  if v_preview.deploy_url is null then
    raise exception 'not_embeddable';
  end if;

  if public.is_preview_team_member(v_preview.id) then
    v_role := 'member';
    v_member := v_uid;
    select coalesce(u.email, 'Team member') into v_name
      from auth.users u where u.id = v_uid;
    if v_name is null then v_name := 'Team member'; end if;
  elsif v_preview.access_mode = 'guest_link'
        and p_link_secret is not null
        and v_preview.link_secret is not null
        and p_link_secret = v_preview.link_secret then
    if v_preview.expires_at is not null and v_preview.expires_at < now() then
      raise exception 'link_expired';
    end if;
    v_role := 'guest';
    v_member := null;
    v_name := 'Guest';
  elsif v_preview.access_mode = 'team_only' and v_uid is null then
    raise exception 'login_required';
  else
    raise exception 'access_denied';
  end if;

  insert into public.review_tokens
    (token, preview_id, role, member_user_id, display_name, expires_at)
  values
    (p_token, v_preview.id, v_role, v_member, v_name, now() + interval '90 seconds');

  return query select p_token, v_preview.deploy_url, v_role;
end;
$$;

revoke all on function public.mint_review_token(text, text, text) from public;
grant execute on function public.mint_review_token(text, text, text) to anon, authenticated;
